services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "UPGRADE",  "http://localhost:8080"]
      interval: 50s
      timeout: 10s
      retries: 5
      start_period: 10s

  mqttx-web:
    image: emqx/mqttx-web
    ports:
      - 80:80 
    container_name: mqttx-web
