services:
  mqtt_broker:
    image: emqx:latest
    container_name: emqx
    env_file:
      - ../.env
    volumes: 
      - ../emqx_volume/data:/opt/emqx/data
      - ../emqx_volume/etc:/opt/emqx/etc
      - ../emqx_volume/log:/opt/emqx/log

    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
      
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
      
    networks:
      - backend

  mqttx_web:
    image: emqx/mqttx-web
    ports:
      - 80:80 
    container_name: mqttx_web

  conceptio_bridges:
    image: ghcr.io/conceptiolab/conceptio_bridges:main
    ports:
      - 9090:9090
      - 9091:9091
    container_name: conceptio_bridges
    env_file:
      - ../.env
    networks:
      - backend
    links:
      - mqtt_broker:emqx
    depends_on:
      mqtt_broker:
        condition: service_healthy

networks:
  backend:
    driver: bridge