services:
  mqtt_broker:
    image: emqx:latest
    container_name: emqx
    env_file:
      - ../.env
    volumes: 
      - ../emqx_volume/data:/opt/emqx/data
      - ../emqx_volume/etc:/opt/emqx/etc
      - ../emqx_volume/log:/opt/emqx/log

    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
      
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
      
    networks:
      - backend

  conceptio_bridges:
    image: ghcr.io/conceptiolab/conceptio_bridges:main
    container_name: conceptio-bridges
    env_file:
      - ../.env
    networks:
      - backend
    depends_on:
      mqtt_broker:
        condition: service_healthy

  conceptio_core:
    image: ghcr.io/conceptiolab/conceptio_core:main
    container_name: conceptio-core
    env_file:
      - ../.env
    networks:
      - backend
    depends_on:
      mqtt_broker:
        condition: service_healthy


networks:
  backend:
    name: backend
    driver: bridge